# -*- coding: utf-8 -*-
"""Streamlit INSS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17P-CHdSx5g4JGzvsc9ps-xbz4xZmK5CY
"""

#===================================================Código para subir Streamlit =========================================#

import streamlit as st
import pandas as pd

# Carregar os dados
st.title("Painel de Análise de INSS - Médicos")

df = pd.read_csv("saida_unificada.csv")

# Tratamento básico
df.columns = df.columns.str.strip()
df = df.fillna("")

# Sidebar com filtros
st.sidebar.header("Filtros")
status_opcao = st.sidebar.multiselect("Status", options=df['STATUS'].unique(), default=df['STATUS'].unique())
hospital_cols = ['OMED', 'HMB', 'HGP', 'PEDRE', 'REDE HC', 'AME CARAP', 'H MULHER', 'HU SBC', 'M BOI', 'AME ITAP', 'H TIRADENTES', 'H ITAIM', 'AME PRADOS']
hospital_opcao = st.sidebar.multiselect("Hospitais", options=hospital_cols, default=hospital_cols)
filtro_inss = st.sidebar.radio("Paga INSS?", options=["Todos", "Sim", "Não"])

# Filtros aplicados
df_filtrado = df[df['STATUS'].isin(status_opcao)]

if filtro_inss == "Sim":
    df_filtrado = df_filtrado[df_filtrado['INSS'] == "S"]
elif filtro_inss == "Não":
    df_filtrado = df_filtrado[df_filtrado['INSS'] == "N"]

# Mostrar resultado
st.subheader("Tabela Filtrada")
st.dataframe(df_filtrado)

# Contagem por hospital
st.subheader("Contagem por Hospital (Ativos)")
df_hospital = df[df['STATUS'] == 'ATIVO']
contagem_hospitais = {col: (df_hospital[col] == 'S').sum() for col in hospital_cols}
df_hospitais_contagem = pd.DataFrame.from_dict(contagem_hospitais, orient='index', columns=['Qtd'])
st.bar_chart(df_hospitais_contagem)

# Lista de pessoas por hospital
st.subheader("Pessoas por Hospital")
hospital_escolhido = st.selectbox("Escolha um hospital", options=hospital_cols)
df_hospital_pessoas = df[df[hospital_escolhido] == 'S'][['NOME', 'CRM', 'STATUS', 'INSS']]
st.dataframe(df_hospital_pessoas)

# Mostrar apenas os NOVOS cadastros
st.subheader("Novos cadastros")
novos = df[df['CONTRATO'].str.upper().str.contains("ENTRADA") | (df['ASSINOU SAIDA'].str.strip() == "")]
st.dataframe(novos[['NOME', 'CRM', 'STATUS', 'INSS', 'CONTRATO']])

# Baixar CSV filtrado
st.download_button("📥 Baixar CSV Filtrado", df_filtrado.to_csv(index=False).encode('utf-8'), "dados_filtrados.csv", "text/csv")